install.packages("tidyverse")
library(tidyverse)

p <- c(number_of_people_with_and_without_electricity_access)
head(p)
str(p)
colnames(p)
install.packages("here")
library("here")
install.packages("skimr")
library("skimr")
install.packages("janitor")
library("janitor")
install.packages("dplyr")
library("dplyr")

p <- c(number_of_people_with_and_without_electricity_access)
skim_without_charts(p)
glimpse(p)
install.packages("tidyverse")
library("tidyverse")
p %>% select(Entity)
install.packages("here")
p %>% rename(Country=Entity)
p %>% arrange(Year)
ggplot(data=number_of_people_with_and_without_electricity_access)+geom_bar(mapping=aes(x=Year,y=Entity))
