install.packages("tidyverse")
library(tidyverse)
install.packages("here")
library(here)
library(lubridate)
library(dplyr)
install.packages("skimr")
library(skimr)
install.packages("janitor")
library(janitor)
library(ggplot2)
read_csv("number-of-people-with-and-without-electricity-access.csv")
p <- read_csv("number-of-people-with-and-without-electricity-access.csv")
str(p)
skim_without_charts(p)
head(p)
glimpse(p)
clean_names(p)
p <- rename(p,Country_name=Entity)
p %>% select(-`Number of people with access to electricity`)
p %>%
  rename(people_having_access_to_electricity=`Number of people with access to electricity`)
p <- rename(p,`Number of people with access to electricity`=people_having_access_to_electricity)
colnames(p)